[machine]
type="zeiss"
dmesn="501717"
dmeswv="6.8.2606"
controllertyp="C32BIT"
dmeswi="Calypso"
dmeid="CONT_G2"

[configuation]
table_file_path=""

[[export]]
type="xml"
xml_result_path="O:\\Measurement\\results"

[[export]]
type="cmm"
cmm_result_path=".\\test_data"

[[export]]
type="mongodb"
uri="mongodb:\\urlToMongodb"
database="cmmData"
collection="results"
